# Generated by Django 4.0.5 on 2022-06-19 05:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime(2022, 6, 19, 1, 25, 51, 966795))),
                ('error_code', models.CharField(max_length=10)),
                ('description', models.TextField()),
            ],
        ),
    ]
