# Generated by Django 4.0.5 on 2022-06-19 05:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Steps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('start_time', models.DateTimeField(default=datetime.datetime(2022, 6, 19, 1, 21, 8, 158852))),
                ('end_time', models.DateTimeField(default=datetime.datetime(2022, 6, 19, 1, 21, 8, 158852))),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.jobs')),
            ],
        ),
    ]
