# Generated by Django 4.0.5 on 2022-06-18 20:14

import django.contrib.postgres.fields
from django.db import migrations, models
import images_processing.apps.jobs.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('steps', django.contrib.postgres.fields.ArrayField(base_field=images_processing.apps.jobs.models.Steps(), default=list, size=None, verbose_name='steps')),
            ],
        ),
    ]
