# Generated by Django 4.0.5 on 2022-06-19 05:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='steps',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 19, 1, 21, 23, 657596)),
        ),
        migrations.AlterField(
            model_name='steps',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 19, 1, 21, 23, 657596)),
        ),
    ]
