# Generated by Django 4.0.5 on 2022-06-19 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_steps_end_time_alter_steps_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='status',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='steps',
            name='status',
            field=models.CharField(max_length=20),
        ),
    ]
