# Generated by Django 4.0.5 on 2022-06-20 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_imagetransformationfsm_current_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagetransformationfsm',
            name='current_image',
        ),
    ]
