# Generated by Django 4.0.5 on 2022-06-20 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_remove_imagetransformationfsm_current_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobs',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='jobs',
            name='status',
            field=models.CharField(default='PROCESS', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='steps',
            name='job_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='jobs.jobs'),
        ),
    ]
