# Generated by Django 4.0.5 on 2022-06-20 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_jobs_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='path_image',
            field=models.FilePathField(default='./static/', null=True),
        ),
    ]
