# Generated by Django 4.0.5 on 2022-06-20 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_jobs_path_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagetransformationfsm',
            name='extension',
        ),
        migrations.AlterField(
            model_name='jobs',
            name='path_image',
            field=models.CharField(default='./static/', max_length=200, null=True),
        ),
    ]
